tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
tp @s ^^^0.1 facing @e[type=marumasa:claw,c=1]
playanimation @a[tag=clawshot1] animation.clawshot.riding animation.humanoid.base_pose 1
playsound dig.chain @a[tag=clawshot1]